# Use the official Bun image as the base image
FROM oven/bun:1.3-debian AS builder

ARG VITE_SERVER_URL

# Set the working directory
WORKDIR /app

RUN apt update -y && apt install curl unzip -y
RUN curl -fsSL https://fnm.vercel.app/install | bash -s --install-dir=/opt/fnm
RUN ln -s /opt/fnm/fnm /usr/bin/fnm
RUN fnm install 24
RUN fnm use 24
RUN corepack enable pnpm
RUN node -v # Should print "v24.11.1".
RUN npm -v
RUN pnpm -v

# Copy package.json and bun.lockb
COPY package.json pnpm-lock.yaml ./
COPY pnpm-workspace.yaml ./
COPY turbo.json ./

# Copy app and packages
COPY apps/web apps/web
COPY packages packages

# Install dependencies
WORKDIR /app/apps/web
RUN pnpm install --frozen-lockfile

ENV VITE_SERVER_URL=${VITE_SERVER_URL}

# Set NODE_ENV to production
ENV NODE_ENV=production

# Build the application
RUN pnpm run -F web build

# Use a lightweight web server to serve the static files
FROM nginx:alpine

# Copy the built assets from the builder stage
COPY --from=builder /app/apps/web/dist /usr/share/nginx/html

# Expose port 80
EXPOSE 80

# Start the nginx server
CMD ["nginx", "-g", "daemon off;"]
