/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DictatorRouteImport } from './routes/dictator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as OrgSlugRouteImport } from './routes/$orgSlug'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DictatorOrgIngredientsRouteImport } from './routes/dictator/org-ingredients'
import { Route as DictatorOrgExercisesRouteImport } from './routes/dictator/org-exercises'
import { Route as DictatorGenerationRouteImport } from './routes/dictator/generation'
import { Route as DictatorBaseIngredientsRouteImport } from './routes/dictator/base-ingredients'
import { Route as DictatorBaseExercisesRouteImport } from './routes/dictator/base-exercises'
import { Route as OrgSlugOrgSlugRecipesRouteImport } from './routes/$orgSlug/$orgSlug.recipes'
import { Route as OrgSlugOrgSlugIngredientsRouteImport } from './routes/$orgSlug/$orgSlug.ingredients'
import { Route as OrgSlugOrgSlugExercisesRouteImport } from './routes/$orgSlug/$orgSlug.exercises'
import { Route as OrgSlugOrgSlugDashboardRouteImport } from './routes/$orgSlug/$orgSlug.dashboard'
import { Route as OrgSlugOrgSlugRecipesCreateRouteImport } from './routes/$orgSlug/$orgSlug.recipes.create'

const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DictatorRoute = DictatorRouteImport.update({
  id: '/dictator',
  path: '/dictator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugRoute = OrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DictatorOrgIngredientsRoute = DictatorOrgIngredientsRouteImport.update({
  id: '/org-ingredients',
  path: '/org-ingredients',
  getParentRoute: () => DictatorRoute,
} as any)
const DictatorOrgExercisesRoute = DictatorOrgExercisesRouteImport.update({
  id: '/org-exercises',
  path: '/org-exercises',
  getParentRoute: () => DictatorRoute,
} as any)
const DictatorGenerationRoute = DictatorGenerationRouteImport.update({
  id: '/generation',
  path: '/generation',
  getParentRoute: () => DictatorRoute,
} as any)
const DictatorBaseIngredientsRoute = DictatorBaseIngredientsRouteImport.update({
  id: '/base-ingredients',
  path: '/base-ingredients',
  getParentRoute: () => DictatorRoute,
} as any)
const DictatorBaseExercisesRoute = DictatorBaseExercisesRouteImport.update({
  id: '/base-exercises',
  path: '/base-exercises',
  getParentRoute: () => DictatorRoute,
} as any)
const OrgSlugOrgSlugRecipesRoute = OrgSlugOrgSlugRecipesRouteImport.update({
  id: '/$orgSlug/recipes',
  path: '/$orgSlug/recipes',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugOrgSlugIngredientsRoute =
  OrgSlugOrgSlugIngredientsRouteImport.update({
    id: '/$orgSlug/ingredients',
    path: '/$orgSlug/ingredients',
    getParentRoute: () => OrgSlugRoute,
  } as any)
const OrgSlugOrgSlugExercisesRoute = OrgSlugOrgSlugExercisesRouteImport.update({
  id: '/$orgSlug/exercises',
  path: '/$orgSlug/exercises',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugOrgSlugDashboardRoute = OrgSlugOrgSlugDashboardRouteImport.update({
  id: '/$orgSlug/dashboard',
  path: '/$orgSlug/dashboard',
  getParentRoute: () => OrgSlugRoute,
} as any)
const OrgSlugOrgSlugRecipesCreateRoute =
  OrgSlugOrgSlugRecipesCreateRouteImport.update({
    id: '/create',
    path: '/create',
    getParentRoute: () => OrgSlugOrgSlugRecipesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/dictator': typeof DictatorRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/dictator/base-exercises': typeof DictatorBaseExercisesRoute
  '/dictator/base-ingredients': typeof DictatorBaseIngredientsRoute
  '/dictator/generation': typeof DictatorGenerationRoute
  '/dictator/org-exercises': typeof DictatorOrgExercisesRoute
  '/dictator/org-ingredients': typeof DictatorOrgIngredientsRoute
  '/$orgSlug/$orgSlug/dashboard': typeof OrgSlugOrgSlugDashboardRoute
  '/$orgSlug/$orgSlug/exercises': typeof OrgSlugOrgSlugExercisesRoute
  '/$orgSlug/$orgSlug/ingredients': typeof OrgSlugOrgSlugIngredientsRoute
  '/$orgSlug/$orgSlug/recipes': typeof OrgSlugOrgSlugRecipesRouteWithChildren
  '/$orgSlug/$orgSlug/recipes/create': typeof OrgSlugOrgSlugRecipesCreateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/dictator': typeof DictatorRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/dictator/base-exercises': typeof DictatorBaseExercisesRoute
  '/dictator/base-ingredients': typeof DictatorBaseIngredientsRoute
  '/dictator/generation': typeof DictatorGenerationRoute
  '/dictator/org-exercises': typeof DictatorOrgExercisesRoute
  '/dictator/org-ingredients': typeof DictatorOrgIngredientsRoute
  '/$orgSlug/$orgSlug/dashboard': typeof OrgSlugOrgSlugDashboardRoute
  '/$orgSlug/$orgSlug/exercises': typeof OrgSlugOrgSlugExercisesRoute
  '/$orgSlug/$orgSlug/ingredients': typeof OrgSlugOrgSlugIngredientsRoute
  '/$orgSlug/$orgSlug/recipes': typeof OrgSlugOrgSlugRecipesRouteWithChildren
  '/$orgSlug/$orgSlug/recipes/create': typeof OrgSlugOrgSlugRecipesCreateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$orgSlug': typeof OrgSlugRouteWithChildren
  '/admin': typeof AdminRoute
  '/dashboard': typeof DashboardRoute
  '/dictator': typeof DictatorRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/dictator/base-exercises': typeof DictatorBaseExercisesRoute
  '/dictator/base-ingredients': typeof DictatorBaseIngredientsRoute
  '/dictator/generation': typeof DictatorGenerationRoute
  '/dictator/org-exercises': typeof DictatorOrgExercisesRoute
  '/dictator/org-ingredients': typeof DictatorOrgIngredientsRoute
  '/$orgSlug/$orgSlug/dashboard': typeof OrgSlugOrgSlugDashboardRoute
  '/$orgSlug/$orgSlug/exercises': typeof OrgSlugOrgSlugExercisesRoute
  '/$orgSlug/$orgSlug/ingredients': typeof OrgSlugOrgSlugIngredientsRoute
  '/$orgSlug/$orgSlug/recipes': typeof OrgSlugOrgSlugRecipesRouteWithChildren
  '/$orgSlug/$orgSlug/recipes/create': typeof OrgSlugOrgSlugRecipesCreateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/dashboard'
    | '/dictator'
    | '/login'
    | '/onboard'
    | '/dictator/base-exercises'
    | '/dictator/base-ingredients'
    | '/dictator/generation'
    | '/dictator/org-exercises'
    | '/dictator/org-ingredients'
    | '/$orgSlug/$orgSlug/dashboard'
    | '/$orgSlug/$orgSlug/exercises'
    | '/$orgSlug/$orgSlug/ingredients'
    | '/$orgSlug/$orgSlug/recipes'
    | '/$orgSlug/$orgSlug/recipes/create'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/dashboard'
    | '/dictator'
    | '/login'
    | '/onboard'
    | '/dictator/base-exercises'
    | '/dictator/base-ingredients'
    | '/dictator/generation'
    | '/dictator/org-exercises'
    | '/dictator/org-ingredients'
    | '/$orgSlug/$orgSlug/dashboard'
    | '/$orgSlug/$orgSlug/exercises'
    | '/$orgSlug/$orgSlug/ingredients'
    | '/$orgSlug/$orgSlug/recipes'
    | '/$orgSlug/$orgSlug/recipes/create'
  id:
    | '__root__'
    | '/'
    | '/$orgSlug'
    | '/admin'
    | '/dashboard'
    | '/dictator'
    | '/login'
    | '/onboard'
    | '/dictator/base-exercises'
    | '/dictator/base-ingredients'
    | '/dictator/generation'
    | '/dictator/org-exercises'
    | '/dictator/org-ingredients'
    | '/$orgSlug/$orgSlug/dashboard'
    | '/$orgSlug/$orgSlug/exercises'
    | '/$orgSlug/$orgSlug/ingredients'
    | '/$orgSlug/$orgSlug/recipes'
    | '/$orgSlug/$orgSlug/recipes/create'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OrgSlugRoute: typeof OrgSlugRouteWithChildren
  AdminRoute: typeof AdminRoute
  DashboardRoute: typeof DashboardRoute
  DictatorRoute: typeof DictatorRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictator': {
      id: '/dictator'
      path: '/dictator'
      fullPath: '/dictator'
      preLoaderRoute: typeof DictatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug': {
      id: '/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/$orgSlug'
      preLoaderRoute: typeof OrgSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictator/org-ingredients': {
      id: '/dictator/org-ingredients'
      path: '/org-ingredients'
      fullPath: '/dictator/org-ingredients'
      preLoaderRoute: typeof DictatorOrgIngredientsRouteImport
      parentRoute: typeof DictatorRoute
    }
    '/dictator/org-exercises': {
      id: '/dictator/org-exercises'
      path: '/org-exercises'
      fullPath: '/dictator/org-exercises'
      preLoaderRoute: typeof DictatorOrgExercisesRouteImport
      parentRoute: typeof DictatorRoute
    }
    '/dictator/generation': {
      id: '/dictator/generation'
      path: '/generation'
      fullPath: '/dictator/generation'
      preLoaderRoute: typeof DictatorGenerationRouteImport
      parentRoute: typeof DictatorRoute
    }
    '/dictator/base-ingredients': {
      id: '/dictator/base-ingredients'
      path: '/base-ingredients'
      fullPath: '/dictator/base-ingredients'
      preLoaderRoute: typeof DictatorBaseIngredientsRouteImport
      parentRoute: typeof DictatorRoute
    }
    '/dictator/base-exercises': {
      id: '/dictator/base-exercises'
      path: '/base-exercises'
      fullPath: '/dictator/base-exercises'
      preLoaderRoute: typeof DictatorBaseExercisesRouteImport
      parentRoute: typeof DictatorRoute
    }
    '/$orgSlug/$orgSlug/recipes': {
      id: '/$orgSlug/$orgSlug/recipes'
      path: '/$orgSlug/recipes'
      fullPath: '/$orgSlug/$orgSlug/recipes'
      preLoaderRoute: typeof OrgSlugOrgSlugRecipesRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/$orgSlug/ingredients': {
      id: '/$orgSlug/$orgSlug/ingredients'
      path: '/$orgSlug/ingredients'
      fullPath: '/$orgSlug/$orgSlug/ingredients'
      preLoaderRoute: typeof OrgSlugOrgSlugIngredientsRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/$orgSlug/exercises': {
      id: '/$orgSlug/$orgSlug/exercises'
      path: '/$orgSlug/exercises'
      fullPath: '/$orgSlug/$orgSlug/exercises'
      preLoaderRoute: typeof OrgSlugOrgSlugExercisesRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/$orgSlug/dashboard': {
      id: '/$orgSlug/$orgSlug/dashboard'
      path: '/$orgSlug/dashboard'
      fullPath: '/$orgSlug/$orgSlug/dashboard'
      preLoaderRoute: typeof OrgSlugOrgSlugDashboardRouteImport
      parentRoute: typeof OrgSlugRoute
    }
    '/$orgSlug/$orgSlug/recipes/create': {
      id: '/$orgSlug/$orgSlug/recipes/create'
      path: '/create'
      fullPath: '/$orgSlug/$orgSlug/recipes/create'
      preLoaderRoute: typeof OrgSlugOrgSlugRecipesCreateRouteImport
      parentRoute: typeof OrgSlugOrgSlugRecipesRoute
    }
  }
}

interface OrgSlugOrgSlugRecipesRouteChildren {
  OrgSlugOrgSlugRecipesCreateRoute: typeof OrgSlugOrgSlugRecipesCreateRoute
}

const OrgSlugOrgSlugRecipesRouteChildren: OrgSlugOrgSlugRecipesRouteChildren = {
  OrgSlugOrgSlugRecipesCreateRoute: OrgSlugOrgSlugRecipesCreateRoute,
}

const OrgSlugOrgSlugRecipesRouteWithChildren =
  OrgSlugOrgSlugRecipesRoute._addFileChildren(
    OrgSlugOrgSlugRecipesRouteChildren,
  )

interface OrgSlugRouteChildren {
  OrgSlugOrgSlugDashboardRoute: typeof OrgSlugOrgSlugDashboardRoute
  OrgSlugOrgSlugExercisesRoute: typeof OrgSlugOrgSlugExercisesRoute
  OrgSlugOrgSlugIngredientsRoute: typeof OrgSlugOrgSlugIngredientsRoute
  OrgSlugOrgSlugRecipesRoute: typeof OrgSlugOrgSlugRecipesRouteWithChildren
}

const OrgSlugRouteChildren: OrgSlugRouteChildren = {
  OrgSlugOrgSlugDashboardRoute: OrgSlugOrgSlugDashboardRoute,
  OrgSlugOrgSlugExercisesRoute: OrgSlugOrgSlugExercisesRoute,
  OrgSlugOrgSlugIngredientsRoute: OrgSlugOrgSlugIngredientsRoute,
  OrgSlugOrgSlugRecipesRoute: OrgSlugOrgSlugRecipesRouteWithChildren,
}

const OrgSlugRouteWithChildren =
  OrgSlugRoute._addFileChildren(OrgSlugRouteChildren)

interface DictatorRouteChildren {
  DictatorBaseExercisesRoute: typeof DictatorBaseExercisesRoute
  DictatorBaseIngredientsRoute: typeof DictatorBaseIngredientsRoute
  DictatorGenerationRoute: typeof DictatorGenerationRoute
  DictatorOrgExercisesRoute: typeof DictatorOrgExercisesRoute
  DictatorOrgIngredientsRoute: typeof DictatorOrgIngredientsRoute
}

const DictatorRouteChildren: DictatorRouteChildren = {
  DictatorBaseExercisesRoute: DictatorBaseExercisesRoute,
  DictatorBaseIngredientsRoute: DictatorBaseIngredientsRoute,
  DictatorGenerationRoute: DictatorGenerationRoute,
  DictatorOrgExercisesRoute: DictatorOrgExercisesRoute,
  DictatorOrgIngredientsRoute: DictatorOrgIngredientsRoute,
}

const DictatorRouteWithChildren = DictatorRoute._addFileChildren(
  DictatorRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OrgSlugRoute: OrgSlugRouteWithChildren,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  DictatorRoute: DictatorRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
