/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DictatorRouteImport } from './routes/dictator'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DictatorOrgIngredientsRouteImport } from './routes/dictator/org-ingredients'
import { Route as DictatorOrgExercisesRouteImport } from './routes/dictator/org-exercises'
import { Route as DictatorBaseIngredientsRouteImport } from './routes/dictator/base-ingredients'
import { Route as DictatorBaseExercisesRouteImport } from './routes/dictator/base-exercises'
import { Route as DictatorAdminFuncRouteImport } from './routes/dictator/admin-func'
import { Route as OrgSlugAdminSRouteImport } from './routes/$orgSlug/admin.s'
import { Route as OrgSlugAdminSIngredientsRouteImport } from './routes/$orgSlug/admin.s.ingredients'
import { Route as OrgSlugAdminSExercisesRouteImport } from './routes/$orgSlug/admin.s.exercises'
import { Route as OrgSlugAdminSDashboardRouteImport } from './routes/$orgSlug/admin.s.dashboard'

const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DictatorRoute = DictatorRouteImport.update({
  id: '/dictator',
  path: '/dictator',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DictatorOrgIngredientsRoute = DictatorOrgIngredientsRouteImport.update({
  id: '/org-ingredients',
  path: '/org-ingredients',
  getParentRoute: () => DictatorRoute,
} as any)
const DictatorOrgExercisesRoute = DictatorOrgExercisesRouteImport.update({
  id: '/org-exercises',
  path: '/org-exercises',
  getParentRoute: () => DictatorRoute,
} as any)
const DictatorBaseIngredientsRoute = DictatorBaseIngredientsRouteImport.update({
  id: '/base-ingredients',
  path: '/base-ingredients',
  getParentRoute: () => DictatorRoute,
} as any)
const DictatorBaseExercisesRoute = DictatorBaseExercisesRouteImport.update({
  id: '/base-exercises',
  path: '/base-exercises',
  getParentRoute: () => DictatorRoute,
} as any)
const DictatorAdminFuncRoute = DictatorAdminFuncRouteImport.update({
  id: '/admin-func',
  path: '/admin-func',
  getParentRoute: () => DictatorRoute,
} as any)
const OrgSlugAdminSRoute = OrgSlugAdminSRouteImport.update({
  id: '/$orgSlug/admin/s',
  path: '/$orgSlug/admin/s',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgSlugAdminSIngredientsRoute =
  OrgSlugAdminSIngredientsRouteImport.update({
    id: '/ingredients',
    path: '/ingredients',
    getParentRoute: () => OrgSlugAdminSRoute,
  } as any)
const OrgSlugAdminSExercisesRoute = OrgSlugAdminSExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => OrgSlugAdminSRoute,
} as any)
const OrgSlugAdminSDashboardRoute = OrgSlugAdminSDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => OrgSlugAdminSRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dictator': typeof DictatorRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/dictator/admin-func': typeof DictatorAdminFuncRoute
  '/dictator/base-exercises': typeof DictatorBaseExercisesRoute
  '/dictator/base-ingredients': typeof DictatorBaseIngredientsRoute
  '/dictator/org-exercises': typeof DictatorOrgExercisesRoute
  '/dictator/org-ingredients': typeof DictatorOrgIngredientsRoute
  '/$orgSlug/admin/s': typeof OrgSlugAdminSRouteWithChildren
  '/$orgSlug/admin/s/dashboard': typeof OrgSlugAdminSDashboardRoute
  '/$orgSlug/admin/s/exercises': typeof OrgSlugAdminSExercisesRoute
  '/$orgSlug/admin/s/ingredients': typeof OrgSlugAdminSIngredientsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dictator': typeof DictatorRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/dictator/admin-func': typeof DictatorAdminFuncRoute
  '/dictator/base-exercises': typeof DictatorBaseExercisesRoute
  '/dictator/base-ingredients': typeof DictatorBaseIngredientsRoute
  '/dictator/org-exercises': typeof DictatorOrgExercisesRoute
  '/dictator/org-ingredients': typeof DictatorOrgIngredientsRoute
  '/$orgSlug/admin/s': typeof OrgSlugAdminSRouteWithChildren
  '/$orgSlug/admin/s/dashboard': typeof OrgSlugAdminSDashboardRoute
  '/$orgSlug/admin/s/exercises': typeof OrgSlugAdminSExercisesRoute
  '/$orgSlug/admin/s/ingredients': typeof OrgSlugAdminSIngredientsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard': typeof DashboardRoute
  '/dictator': typeof DictatorRouteWithChildren
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/dictator/admin-func': typeof DictatorAdminFuncRoute
  '/dictator/base-exercises': typeof DictatorBaseExercisesRoute
  '/dictator/base-ingredients': typeof DictatorBaseIngredientsRoute
  '/dictator/org-exercises': typeof DictatorOrgExercisesRoute
  '/dictator/org-ingredients': typeof DictatorOrgIngredientsRoute
  '/$orgSlug/admin/s': typeof OrgSlugAdminSRouteWithChildren
  '/$orgSlug/admin/s/dashboard': typeof OrgSlugAdminSDashboardRoute
  '/$orgSlug/admin/s/exercises': typeof OrgSlugAdminSExercisesRoute
  '/$orgSlug/admin/s/ingredients': typeof OrgSlugAdminSIngredientsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/dictator'
    | '/login'
    | '/onboard'
    | '/dictator/admin-func'
    | '/dictator/base-exercises'
    | '/dictator/base-ingredients'
    | '/dictator/org-exercises'
    | '/dictator/org-ingredients'
    | '/$orgSlug/admin/s'
    | '/$orgSlug/admin/s/dashboard'
    | '/$orgSlug/admin/s/exercises'
    | '/$orgSlug/admin/s/ingredients'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/dictator'
    | '/login'
    | '/onboard'
    | '/dictator/admin-func'
    | '/dictator/base-exercises'
    | '/dictator/base-ingredients'
    | '/dictator/org-exercises'
    | '/dictator/org-ingredients'
    | '/$orgSlug/admin/s'
    | '/$orgSlug/admin/s/dashboard'
    | '/$orgSlug/admin/s/exercises'
    | '/$orgSlug/admin/s/ingredients'
  id:
    | '__root__'
    | '/'
    | '/dashboard'
    | '/dictator'
    | '/login'
    | '/onboard'
    | '/dictator/admin-func'
    | '/dictator/base-exercises'
    | '/dictator/base-ingredients'
    | '/dictator/org-exercises'
    | '/dictator/org-ingredients'
    | '/$orgSlug/admin/s'
    | '/$orgSlug/admin/s/dashboard'
    | '/$orgSlug/admin/s/exercises'
    | '/$orgSlug/admin/s/ingredients'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  DictatorRoute: typeof DictatorRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  OrgSlugAdminSRoute: typeof OrgSlugAdminSRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictator': {
      id: '/dictator'
      path: '/dictator'
      fullPath: '/dictator'
      preLoaderRoute: typeof DictatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dictator/org-ingredients': {
      id: '/dictator/org-ingredients'
      path: '/org-ingredients'
      fullPath: '/dictator/org-ingredients'
      preLoaderRoute: typeof DictatorOrgIngredientsRouteImport
      parentRoute: typeof DictatorRoute
    }
    '/dictator/org-exercises': {
      id: '/dictator/org-exercises'
      path: '/org-exercises'
      fullPath: '/dictator/org-exercises'
      preLoaderRoute: typeof DictatorOrgExercisesRouteImport
      parentRoute: typeof DictatorRoute
    }
    '/dictator/base-ingredients': {
      id: '/dictator/base-ingredients'
      path: '/base-ingredients'
      fullPath: '/dictator/base-ingredients'
      preLoaderRoute: typeof DictatorBaseIngredientsRouteImport
      parentRoute: typeof DictatorRoute
    }
    '/dictator/base-exercises': {
      id: '/dictator/base-exercises'
      path: '/base-exercises'
      fullPath: '/dictator/base-exercises'
      preLoaderRoute: typeof DictatorBaseExercisesRouteImport
      parentRoute: typeof DictatorRoute
    }
    '/dictator/admin-func': {
      id: '/dictator/admin-func'
      path: '/admin-func'
      fullPath: '/dictator/admin-func'
      preLoaderRoute: typeof DictatorAdminFuncRouteImport
      parentRoute: typeof DictatorRoute
    }
    '/$orgSlug/admin/s': {
      id: '/$orgSlug/admin/s'
      path: '/$orgSlug/admin/s'
      fullPath: '/$orgSlug/admin/s'
      preLoaderRoute: typeof OrgSlugAdminSRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$orgSlug/admin/s/ingredients': {
      id: '/$orgSlug/admin/s/ingredients'
      path: '/ingredients'
      fullPath: '/$orgSlug/admin/s/ingredients'
      preLoaderRoute: typeof OrgSlugAdminSIngredientsRouteImport
      parentRoute: typeof OrgSlugAdminSRoute
    }
    '/$orgSlug/admin/s/exercises': {
      id: '/$orgSlug/admin/s/exercises'
      path: '/exercises'
      fullPath: '/$orgSlug/admin/s/exercises'
      preLoaderRoute: typeof OrgSlugAdminSExercisesRouteImport
      parentRoute: typeof OrgSlugAdminSRoute
    }
    '/$orgSlug/admin/s/dashboard': {
      id: '/$orgSlug/admin/s/dashboard'
      path: '/dashboard'
      fullPath: '/$orgSlug/admin/s/dashboard'
      preLoaderRoute: typeof OrgSlugAdminSDashboardRouteImport
      parentRoute: typeof OrgSlugAdminSRoute
    }
  }
}

interface DictatorRouteChildren {
  DictatorAdminFuncRoute: typeof DictatorAdminFuncRoute
  DictatorBaseExercisesRoute: typeof DictatorBaseExercisesRoute
  DictatorBaseIngredientsRoute: typeof DictatorBaseIngredientsRoute
  DictatorOrgExercisesRoute: typeof DictatorOrgExercisesRoute
  DictatorOrgIngredientsRoute: typeof DictatorOrgIngredientsRoute
}

const DictatorRouteChildren: DictatorRouteChildren = {
  DictatorAdminFuncRoute: DictatorAdminFuncRoute,
  DictatorBaseExercisesRoute: DictatorBaseExercisesRoute,
  DictatorBaseIngredientsRoute: DictatorBaseIngredientsRoute,
  DictatorOrgExercisesRoute: DictatorOrgExercisesRoute,
  DictatorOrgIngredientsRoute: DictatorOrgIngredientsRoute,
}

const DictatorRouteWithChildren = DictatorRoute._addFileChildren(
  DictatorRouteChildren,
)

interface OrgSlugAdminSRouteChildren {
  OrgSlugAdminSDashboardRoute: typeof OrgSlugAdminSDashboardRoute
  OrgSlugAdminSExercisesRoute: typeof OrgSlugAdminSExercisesRoute
  OrgSlugAdminSIngredientsRoute: typeof OrgSlugAdminSIngredientsRoute
}

const OrgSlugAdminSRouteChildren: OrgSlugAdminSRouteChildren = {
  OrgSlugAdminSDashboardRoute: OrgSlugAdminSDashboardRoute,
  OrgSlugAdminSExercisesRoute: OrgSlugAdminSExercisesRoute,
  OrgSlugAdminSIngredientsRoute: OrgSlugAdminSIngredientsRoute,
}

const OrgSlugAdminSRouteWithChildren = OrgSlugAdminSRoute._addFileChildren(
  OrgSlugAdminSRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  DictatorRoute: DictatorRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  OrgSlugAdminSRoute: OrgSlugAdminSRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
